# Generated by Django 4.2.5 on 2024-02-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='reg',
        ),
    ]
