# Generated by Django 4.2.7 on 2024-02-05 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='item',
        ),
    ]
