# Generated by Django 4.2.7 on 2024-02-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_product_product_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
