# Generated by Django 4.2.7 on 2024-02-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='userid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
