# Generated by Django 4.2.7 on 2024-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_category_subcategory_subitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='userid',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
