# Generated by Django 5.0.2 on 2024-02-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_rename_item_maincategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('discount', models.IntegerField(max_length=100)),
            ],
        ),
    ]
