# Generated by Django 5.0.2 on 2024-02-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pstatus',
            field=models.IntegerField(default=0),
        ),
    ]
