# Generated by Django 5.0.2 on 2024-02-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_product_pstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
