# Generated by Django 5.0.2 on 2024-02-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_delete_product_alter_subcategory_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('pstatus', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
