# Generated by Django 5.0.2 on 2024-02-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_productdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='image',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
