# Generated by Django 5.0.2 on 2024-02-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_productdata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='pcatagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdata',
            name='psubcatagory',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
