# Generated by Django 5.0.2 on 2024-02-28 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_productdata_pcatagory_productdata_psubcatagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productdata',
        ),
    ]
